title: Adrian Salah
email: noname@gmail.com
description: Calculation & Development Engineer

github_username:  adriansalah
linkedin_username: adriansalah

theme: minima


collections:
  notes:
    output: true
